//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public int StatusID { get; set; }
        public bool Status { get; set; }
        public int OrderID { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
